# Generated by Django 5.0.1 on 2024-01-30 13:49

import FormsBasics.web.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35, validators=[FormsBasics.web.models.non_empty_spaces])),
                ('last_name', models.CharField(max_length=35)),
                ('role', models.IntegerField(choices=[(1, 'Software Developer'), (2, 'QA engineer')])),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.department')),
            ],
        ),
    ]
