# Generated by Django 4.2.4 on 2023-10-22 18:47

from django.db import migrations


def change_rarity(apps, schema_editor):
    Item = apps.get_model('main_app', 'Item')

    for item in Item.objects.all():
        if item.price <= 10:
            item.rarity = 'Rare'
        elif 11 <= item.price <= 20:
            item.rarity = 'Very Rare'
        elif 21 <= item.price <= 30:
            item.rarity = 'Extremely Rare'
        else:
            item.rarity = 'Mega Rare'

        item.save()     # Don't forget to save the changes made to the item.


def reverse_rarity(apps, schema_editor):
    Item = apps.get_model('main_app', 'Item')

    for item in Item.objects.all():
        item.rarity = 'empty'

        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(change_rarity, reverse_code=reverse_rarity)
    ]
