# Generated by Django 4.2.4 on 2023-11-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_realestatelisting_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='realestatelisting',
            managers=[
            ],
        ),
    ]
