# Generated by Django 5.0.1 on 2024-01-24 23:15

import Petstagram_workshop.photos.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0002_alter_pet_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', validators=[Petstagram_workshop.photos.validators.validate_file_size])),
                ('description', models.TextField(blank=True, max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('modified_on', models.DateField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('tagged_pets', models.ManyToManyField(blank=True, related_name='photos', to='pets.pet')),
            ],
        ),
    ]
