# Generated by Django 4.2.4 on 2023-10-20 13:33

from django.db import migrations


class Migration(migrations.Migration):

    def change_category(apps, schema_editors):
        Product = apps.get_model("main_app", "Product")
        for product in Product.objects.all():
            if not product.category:
                product.category = ""
                product.save()

    def change_supplier(apps, schema_editors):
        Product = apps.get_model("main_app", "Product")
        for product in Product.objects.all():
            if product.supplier is None:
                product.supplier = ""
                product.save()

    dependencies = [
        ('main_app', '0002_product_created_on_product_last_edited_on'),
    ]

    operations = [
        migrations.RunPython(change_supplier),
        migrations.RunPython(change_category),
    ]
