# Generated by Django 4.2.4 on 2023-10-22 17:52

from django.db import migrations


def generate_age(apps, schema_editors):
    Person = apps.get_model('main_app', 'Person')

    for person in Person.objects.all():
        if person.age <= 12:
            person.age_group = 'Child'
        elif 12 < person.age <= 17:
            person.age_group = 'Teen'
        else:
            person.age_group = 'Adult'
        person.save()


def reverse_age(apps, schema_editors):
    Person = apps.get_model('main_app', 'Person')

    for person in Person.objects.all():
        person.age_group = 'No age group'
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(generate_age, reverse_code=reverse_age)
    ]
