# Generated by Django 5.0.2 on 2024-02-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_type',
            field=models.CharField(choices=[('P', 'Petrol'), ('D', 'Diesel'), ('H', 'Hybrid'), ('E', 'Electric'), (None, None)], max_length=15),
        ),
    ]
